# Generated by Django 5.1.4 on 2025-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(blank=True, max_length=250, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_quantity_int', models.IntegerField(blank=True, null=True)),
                ('product_quantity_float', models.FloatField(blank=True, null=True)),
                ('product_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
