# Generated by Django 5.1.4 on 2025-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_contact_product_product_category_product_product_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasification_title', models.CharField(blank=True, max_length=250, null=True)),
                ('clasification_image', models.ImageField(blank=True, null=True, upload_to='clasification/')),
            ],
        ),
    ]
