# Generated by Django 5.1.4 on 2025-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_clasification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasification',
            name='clasification_image',
            field=models.ImageField(blank=True, null=True, upload_to='clasifications/'),
        ),
    ]
