# Generated by Django 5.1.4 on 2025-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_item_delete_clasification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_title', models.CharField(blank=True, max_length=250, null=True)),
                ('arrival_image', models.ImageField(blank=True, null=True, upload_to='arrival/')),
            ],
        ),
    ]
