# Generated by Django 5.1.4 on 2025-01-22 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantity_float',
        ),
        migrations.AddField(
            model_name='product',
            name='product_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.item'),
        ),
    ]
