# Generated by Django 5.1.5 on 2025-01-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_product_product_quantity_float_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='arrival_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='arrival',
            name='arrival_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
